# Generated by Django 5.2 on 2025-04-29 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generada', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(help_text='Descripción breve del patrón detectado o posible riesgo.')),
                ('nivel_riesgo', models.CharField(choices=[('Bajo', 'Bajo'), ('Moderado', 'Moderado'), ('Alto', 'Alto')], default='Moderado', max_length=20)),
                ('resuelta', models.BooleanField(default=False, help_text='Marcar como resuelta una vez que el médico la revise.')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
