# Generated by Django 5.2 on 2026-07-03 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0001_initial'),
        ('historial_clinico', '0003_alter_enfermedad_options_alter_sintoma_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertaclinica',
            name='enfermedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='historial_clinico.enfermedad'),
        ),
    ]
