# Generated by Django 5.2 on 2026-07-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_clinico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('sintomas', models.ManyToManyField(related_name='enfermedades', to='historial_clinico.sintoma')),
            ],
        ),
        migrations.AddField(
            model_name='registroclinico',
            name='sintomas',
            field=models.ManyToManyField(blank=True, related_name='registros_clinicos', to='historial_clinico.sintoma'),
        ),
    ]
