# Generated by Django 5.2 on 2026-07-02 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historial_clinico', '0002_sintoma_enfermedad_registroclinico_sintomas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enfermedad',
            options={'verbose_name': 'Enfermedad', 'verbose_name_plural': 'Enfermedades'},
        ),
        migrations.AlterModelOptions(
            name='sintoma',
            options={'verbose_name': 'Síntoma', 'verbose_name_plural': 'Síntomas'},
        ),
    ]
